### ISSUE TITLE
Static linking fails with gcc 4.9.3

### ISSUE THREAD

**Issue by mjigmond** [dwelter/pestpp#4]
I am having trouble completing the compile with gcc-4.9.3. Everything seems to compile fine until it needs to statically link the objects. Dynamic linking appears to work.
```bash
g++ pest++.o -pthread -std=c++11 -Wl,--no-as-needed -O2 -static -static-libgcc -static-libgfortran -L /usr/local/gcc-4.9.3/lib64 -L /usr/lib/x86_64-redhat-linux5E/lib64 -L ../common -L ../iopp -L ../yamr -L ../pestpp_common -L ../pest_routines  -L ../propack -L ../linear_analysis -lpestpp_com -lrunmanager  -liopp  -lcommon -lpest_routines -l propack -llapack -lblas -llinear_analysis -lgfortran /usr/local/gcc-4.9.3/lib64/libquadmath.a -o pestpp
../common/libcommon.a(system_variables.o): In function `OperSys::gets_s(char*, unsigned long)':
system_variables.cpp:(.text+0x51): warning: the `gets' function is dangerous and should not be used.
../common/libcommon.a(network_wrapper.o): In function `w_getaddrinfo(char const*, char const*, addrinfo const*, addrinfo**)':
network_wrapper.cpp:(.text+0x37): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/local/gcc-4.9.3/lib64/libgfortran.a(unix.o): In function `tempfile_open':
/workspace/software/gcc-4.9.3/libgfortran/io/unix.c:1137: undefined reference to `mkostemp'
collect2: error: ld returned 1 exit status
make[1]: *** [pestpp] Error 1
make[1]: Leaving directory `/workspace/software/pestpp/pest++/pest++'
make: *** [all] Error 2
```

Using
```bash
[mjigmond@head pest++]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/gcc-4.9.3/libexec/gcc/x86_64-unknown-linux-gnu/4.9.3/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: /workspace/software/gcc-4.9.3/configure --prefix=/usr/local/gcc-4.9.3 --bindir=/usr/local/bin --disable-multilib --with-system-zlib --enable-languages=c,c++,fortran,go
Thread model: posix
gcc version 4.9.3 (GCC)
```

**Comment by jtwhite79** [comment]
Hey Marius - have you tried compiling with gcc (g++ and gfortran) 5.2?  I don't build for linux, but I know Dave has upgraded the support to 5.2 and I just verified that pestpp will build on mac with 5.2.  If that's not it, then can you post some more specifics about your linux setup?

**Comment by mjigmond** [comment]
Jeremy, I tried with 5.3.0 but I'm having linking issues as well. I'll try and compile 5.2.0 and see if it makes a difference. Objects compile fine but linking fails for both static and dynamic with 5.3.0. Given that the objects appear to compile fine I suspect it's failing to find the proper libs at link time.
Dynamic linking
```bash
g++ pest++.o -pthread -std=c++11 -Wl,--no-as-needed -O2  -L/usr/local/gcc-5.3.0/lib/../lib64 -L/usr/lib/x86_64-redhat-linux5E/lib64 -L ../common -L ../iopp -L ../yamr -L ../pestpp_common -L ../pest_routines  -L ../propack -L ../linear_analysis -lpestpp_com -lrunmanager  -liopp  -lcommon -lpest_routines -l propack -llapack -lblas -llinear_analysis -lgfortran /usr/local/gcc-5.3.0/lib/../lib64/libquadmath.a -o pestpp
/usr/lib/../lib64/crt1.o: In function `_start':
(.text+0x12): undefined reference to `__libc_csu_fini'
/usr/lib/../lib64/crt1.o: In function `_start':
(.text+0x19): undefined reference to `__libc_csu_init'
/usr/local/gcc-5.3.0/lib/../lib64/libgfortran.so: undefined reference to `strerror_l@GLIBC_2.6'
/usr/local/gcc-5.3.0/lib/../lib64/libquadmath.so.0: undefined reference to `register_printf_modifier@GLIBC_2.10'
/usr/local/gcc-5.3.0/lib/../lib64/libquadmath.so.0: undefined reference to `register_printf_type@GLIBC_2.10'
/usr/local/gcc-5.3.0/lib/../lib64/libquadmath.so.0: undefined reference to `register_printf_specifier@GLIBC_2.10'
/usr/local/gcc-5.3.0/lib/../lib64/libgfortran.so: undefined reference to `mkostemp@GLIBC_2.7'
collect2: error: ld returned 1 exit status
make[1]: *** [pestpp] Error 1
make[1]: Leaving directory `/workspace/software/pestpp/pest++/pest++'
make: *** [all] Error 2
```

Static linking
```bash
g++ pest++.o -pthread -std=c++11 -Wl,--no-as-needed -O2 -static -static-libgcc -static-libgfortran -L/usr/local/gcc-5.3.0/lib/../lib64 -L/usr/lib/x86_64-redhat-linux5E/lib64 -L ../common -L ../iopp -L ../yamr -L ../pestpp_common -L ../pest_routines  -L ../propack -L ../linear_analysis -lpestpp_com -lrunmanager  -liopp  -lcommon -lpest_routines -l propack -llapack -lblas -llinear_analysis -lgfortran /usr/local/gcc-5.3.0/lib/../lib64/libquadmath.a -o pestpp
../common/libcommon.a(system_variables.o): In function `OperSys::gets_s(char*, unsigned long)':
system_variables.cpp:(.text+0x6b1): warning: the `gets' function is dangerous and should not be used.
../common/libcommon.a(network_wrapper.o): In function `w_getaddrinfo(char const*, char const*, addrinfo const*, addrinfo**)':
network_wrapper.cpp:(.text+0xe7): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/local/gcc-5.3.0/lib/../lib64/libgfortran.a(error.o): In function `_gfortrani_gf_strerror':
/workspace/software/gcc-5.3.0/libgfortran/runtime/error.c:227: undefined reference to `strerror_l'
/usr/local/gcc-5.3.0/lib/../lib64/libgfortran.a(unix.o): In function `tempfile_open':
/workspace/software/gcc-5.3.0/libgfortran/io/unix.c:1132: undefined reference to `mkostemp'
collect2: error: ld returned 1 exit status
make[1]: *** [pestpp] Error 1
make[1]: Leaving directory `/workspace/software/pestpp/pest++/pest++'
make: *** [all] Error 2
```

**Comment by jtwhite79** [comment]
This maybe a dumb question, but have you tired to compile any other mixed language apps using your current setup?  I'm past my understanding of Linux mixed language linker issues but just wondering if your install is working for other apps?

**Comment by mjigmond** [comment]
Followed your suggestion and tried to compile mf2005 (GMG solver is in C) with gcc-5.3.0 and I ran into similar issues. The problem stems from the static linking which I discovered is largely not recommended on Linux systems according to https://software.intel.com/en-us/articles/error-ld-cannot-find-lm. Installing "glibc-static" on our system (CentOS 6.4) solved my problem. I can confirm that compiling works with gcc-5.3.0 with either static or dynamic linking.
